// Code generated by go-swagger; DO NOT EDIT.

// Package restapi acnh
//
//  Schemes:
//    http
//  Host: localhost:8322
//  BasePath: /api/v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
