// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "acnh",
    "version": "1.0.0"
  },
  "host": "localhost:8322",
  "basePath": "/api/v1",
  "paths": {
    "/catalog/bugs": {
      "get": {
        "tags": [
          "bug"
        ],
        "operationId": "listBugs",
        "parameters": [
          {
            "$ref": "#/parameters/Cursor"
          },
          {
            "$ref": "#/parameters/PageSize"
          },
          {
            "$ref": "#/parameters/SortBy"
          }
        ],
        "responses": {
          "200": {
            "description": "return a list of bugs",
            "schema": {
              "$ref": "#/definitions/BugListResult"
            }
          }
        }
      }
    },
    "/catalog/bugs/{id}": {
      "get": {
        "tags": [
          "bug"
        ],
        "operationId": "getBug",
        "parameters": [
          {
            "type": "integer",
            "description": "Numeric ID of the bug to get.",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "return a bug",
            "schema": {
              "$ref": "#/definitions/Bug"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/catalog/fishes": {
      "get": {
        "tags": [
          "fish"
        ],
        "operationId": "listFishes",
        "parameters": [
          {
            "$ref": "#/parameters/Cursor"
          },
          {
            "$ref": "#/parameters/PageSize"
          },
          {
            "$ref": "#/parameters/SortBy"
          }
        ],
        "responses": {
          "200": {
            "description": "returns a list of fishes",
            "schema": {
              "$ref": "#/definitions/FishListResult"
            }
          }
        }
      }
    },
    "/catalog/fishes/{id}": {
      "get": {
        "tags": [
          "fish"
        ],
        "operationId": "getFish",
        "parameters": [
          {
            "type": "integer",
            "description": "Numeric ID of the fish to get.",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "return a fish",
            "schema": {
              "$ref": "#/definitions/Fish"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    }
  },
  "definitions": {
    "Availability": {
      "type": "object",
      "properties": {
        "hours": {
          "description": "availability by hour range",
          "type": "array",
          "items": {
            "type": "array",
            "maxLength": 2,
            "minLength": 2,
            "items": {
              "type": "string"
            }
          }
        },
        "location": {
          "type": "string"
        },
        "months": {
          "$ref": "#/definitions/Months"
        },
        "rarity": {
          "$ref": "#/definitions/Rarity"
        },
        "weather": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Weather"
          }
        }
      }
    },
    "Bug": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Resource"
        },
        {
          "type": "object",
          "properties": {
            "availability": {
              "$ref": "#/definitions/Availability"
            },
            "price": {
              "type": "number",
              "format": "integer"
            },
            "shadow": {
              "type": "string"
            }
          }
        }
      ]
    },
    "BugListResult": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/ListResult"
        },
        {
          "type": "object",
          "properties": {
            "results": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Bug"
              }
            }
          }
        }
      ]
    },
    "Fish": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Resource"
        },
        {
          "type": "object",
          "properties": {
            "availability": {
              "$ref": "#/definitions/Availability"
            },
            "price": {
              "type": "number",
              "format": "integer"
            },
            "shadow": {
              "type": "string"
            }
          }
        }
      ]
    },
    "FishListResult": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/ListResult"
        },
        {
          "type": "object",
          "properties": {
            "results": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Fish"
              }
            }
          }
        }
      ]
    },
    "ListResult": {
      "description": "The list object",
      "type": "object",
      "properties": {
        "page_cursor": {
          "description": "result count",
          "type": "string"
        },
        "result_count": {
          "type": "integer",
          "readOnly": true
        }
      }
    },
    "Months": {
      "type": "object",
      "properties": {
        "northern": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "southern": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      }
    },
    "Name": {
      "type": "object",
      "properties": {
        "name_cn": {
          "description": "chinese",
          "type": "string"
        },
        "name_en": {
          "description": "english",
          "type": "string"
        }
      }
    },
    "Rarity": {
      "type": "string",
      "enum": [
        "Common",
        "Uncommon",
        "Rare",
        "Ultra-rare"
      ]
    },
    "Resource": {
      "description": "The basic object",
      "type": "object",
      "required": [
        "id",
        "name",
        "resource_type"
      ],
      "properties": {
        "id": {
          "description": "id",
          "type": "integer"
        },
        "name": {
          "$ref": "#/definitions/Name"
        },
        "resource_type": {
          "description": "type of the resource",
          "type": "string"
        }
      },
      "discriminator": "resource_type"
    },
    "Weather": {
      "type": "string",
      "enum": [
        "Any",
        "Rain",
        "Snow"
      ]
    }
  },
  "parameters": {
    "Cursor": {
      "type": "string",
      "name": "cursor",
      "in": "query"
    },
    "PageSize": {
      "maximum": 1000,
      "type": "integer",
      "default": 20,
      "description": "Maximal number of record return in one page, server may return less.",
      "name": "page_size",
      "in": "query"
    },
    "SortBy": {
      "type": "string",
      "description": "Fields by which the records are sorted",
      "name": "sort_by",
      "in": "query"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "title": "acnh",
    "version": "1.0.0"
  },
  "host": "localhost:8322",
  "basePath": "/api/v1",
  "paths": {
    "/catalog/bugs": {
      "get": {
        "tags": [
          "bug"
        ],
        "operationId": "listBugs",
        "parameters": [
          {
            "type": "string",
            "name": "cursor",
            "in": "query"
          },
          {
            "maximum": 1000,
            "minimum": 0,
            "type": "integer",
            "default": 20,
            "description": "Maximal number of record return in one page, server may return less.",
            "name": "page_size",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Fields by which the records are sorted",
            "name": "sort_by",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "return a list of bugs",
            "schema": {
              "$ref": "#/definitions/BugListResult"
            }
          }
        }
      }
    },
    "/catalog/bugs/{id}": {
      "get": {
        "tags": [
          "bug"
        ],
        "operationId": "getBug",
        "parameters": [
          {
            "type": "integer",
            "description": "Numeric ID of the bug to get.",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "return a bug",
            "schema": {
              "$ref": "#/definitions/Bug"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    },
    "/catalog/fishes": {
      "get": {
        "tags": [
          "fish"
        ],
        "operationId": "listFishes",
        "parameters": [
          {
            "type": "string",
            "name": "cursor",
            "in": "query"
          },
          {
            "maximum": 1000,
            "minimum": 0,
            "type": "integer",
            "default": 20,
            "description": "Maximal number of record return in one page, server may return less.",
            "name": "page_size",
            "in": "query"
          },
          {
            "type": "string",
            "description": "Fields by which the records are sorted",
            "name": "sort_by",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "returns a list of fishes",
            "schema": {
              "$ref": "#/definitions/FishListResult"
            }
          }
        }
      }
    },
    "/catalog/fishes/{id}": {
      "get": {
        "tags": [
          "fish"
        ],
        "operationId": "getFish",
        "parameters": [
          {
            "type": "integer",
            "description": "Numeric ID of the fish to get.",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "return a fish",
            "schema": {
              "$ref": "#/definitions/Fish"
            }
          },
          "404": {
            "description": "not found"
          }
        }
      }
    }
  },
  "definitions": {
    "Availability": {
      "type": "object",
      "properties": {
        "hours": {
          "description": "availability by hour range",
          "type": "array",
          "items": {
            "type": "array",
            "maxLength": 2,
            "minLength": 2,
            "items": {
              "type": "string"
            }
          }
        },
        "location": {
          "type": "string"
        },
        "months": {
          "$ref": "#/definitions/Months"
        },
        "rarity": {
          "$ref": "#/definitions/Rarity"
        },
        "weather": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Weather"
          }
        }
      }
    },
    "Bug": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Resource"
        },
        {
          "type": "object",
          "properties": {
            "availability": {
              "$ref": "#/definitions/Availability"
            },
            "price": {
              "type": "number",
              "format": "integer"
            },
            "shadow": {
              "type": "string"
            }
          }
        }
      ]
    },
    "BugListResult": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/ListResult"
        },
        {
          "type": "object",
          "properties": {
            "results": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Bug"
              }
            }
          }
        }
      ]
    },
    "Fish": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Resource"
        },
        {
          "type": "object",
          "properties": {
            "availability": {
              "$ref": "#/definitions/Availability"
            },
            "price": {
              "type": "number",
              "format": "integer"
            },
            "shadow": {
              "type": "string"
            }
          }
        }
      ]
    },
    "FishListResult": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/ListResult"
        },
        {
          "type": "object",
          "properties": {
            "results": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Fish"
              }
            }
          }
        }
      ]
    },
    "ListResult": {
      "description": "The list object",
      "type": "object",
      "properties": {
        "page_cursor": {
          "description": "result count",
          "type": "string"
        },
        "result_count": {
          "type": "integer",
          "readOnly": true
        }
      }
    },
    "Months": {
      "type": "object",
      "properties": {
        "northern": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "southern": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      }
    },
    "Name": {
      "type": "object",
      "properties": {
        "name_cn": {
          "description": "chinese",
          "type": "string"
        },
        "name_en": {
          "description": "english",
          "type": "string"
        }
      }
    },
    "Rarity": {
      "type": "string",
      "enum": [
        "Common",
        "Uncommon",
        "Rare",
        "Ultra-rare"
      ]
    },
    "Resource": {
      "description": "The basic object",
      "type": "object",
      "required": [
        "id",
        "name",
        "resource_type"
      ],
      "properties": {
        "id": {
          "description": "id",
          "type": "integer"
        },
        "name": {
          "$ref": "#/definitions/Name"
        },
        "resource_type": {
          "description": "type of the resource",
          "type": "string"
        }
      },
      "discriminator": "resource_type"
    },
    "Weather": {
      "type": "string",
      "enum": [
        "Any",
        "Rain",
        "Snow"
      ]
    }
  },
  "parameters": {
    "Cursor": {
      "type": "string",
      "name": "cursor",
      "in": "query"
    },
    "PageSize": {
      "maximum": 1000,
      "minimum": 0,
      "type": "integer",
      "default": 20,
      "description": "Maximal number of record return in one page, server may return less.",
      "name": "page_size",
      "in": "query"
    },
    "SortBy": {
      "type": "string",
      "description": "Fields by which the records are sorted",
      "name": "sort_by",
      "in": "query"
    }
  }
}`))
}
