// Code generated by go-swagger; DO NOT EDIT.

package bug

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBugHandlerFunc turns a function with the right signature into a get bug handler
type GetBugHandlerFunc func(GetBugParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBugHandlerFunc) Handle(params GetBugParams) middleware.Responder {
	return fn(params)
}

// GetBugHandler interface for that can handle valid get bug params
type GetBugHandler interface {
	Handle(GetBugParams) middleware.Responder
}

// NewGetBug creates a new http.Handler for the get bug operation
func NewGetBug(ctx *middleware.Context, handler GetBugHandler) *GetBug {
	return &GetBug{Context: ctx, Handler: handler}
}

/*GetBug swagger:route GET /catalog/bugs/{id} bug getBug

GetBug get bug API

*/
type GetBug struct {
	Context *middleware.Context
	Handler GetBugHandler
}

func (o *GetBug) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBugParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
