// Code generated by go-swagger; DO NOT EDIT.

package bug

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/yishanhe/animalcrossing-api/models"
)

// GetBugOKCode is the HTTP code returned for type GetBugOK
const GetBugOKCode int = 200

/*GetBugOK return a bug

swagger:response getBugOK
*/
type GetBugOK struct {

	/*
	  In: Body
	*/
	Payload *models.Bug `json:"body,omitempty"`
}

// NewGetBugOK creates GetBugOK with default headers values
func NewGetBugOK() *GetBugOK {

	return &GetBugOK{}
}

// WithPayload adds the payload to the get bug o k response
func (o *GetBugOK) WithPayload(payload *models.Bug) *GetBugOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bug o k response
func (o *GetBugOK) SetPayload(payload *models.Bug) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBugOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBugNotFoundCode is the HTTP code returned for type GetBugNotFound
const GetBugNotFoundCode int = 404

/*GetBugNotFound not found

swagger:response getBugNotFound
*/
type GetBugNotFound struct {
}

// NewGetBugNotFound creates GetBugNotFound with default headers values
func NewGetBugNotFound() *GetBugNotFound {

	return &GetBugNotFound{}
}

// WriteResponse to the client
func (o *GetBugNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
