// Code generated by go-swagger; DO NOT EDIT.

package bug

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/yishanhe/animalcrossing-api/models"
)

// ListBugsOKCode is the HTTP code returned for type ListBugsOK
const ListBugsOKCode int = 200

/*ListBugsOK returns a list of fishes

swagger:response listBugsOK
*/
type ListBugsOK struct {

	/*
	  In: Body
	*/
	Payload *models.BugListResult `json:"body,omitempty"`
}

// NewListBugsOK creates ListBugsOK with default headers values
func NewListBugsOK() *ListBugsOK {

	return &ListBugsOK{}
}

// WithPayload adds the payload to the list bugs o k response
func (o *ListBugsOK) WithPayload(payload *models.BugListResult) *ListBugsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list bugs o k response
func (o *ListBugsOK) SetPayload(payload *models.BugListResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListBugsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
