// Code generated by go-swagger; DO NOT EDIT.

package fish

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetFishHandlerFunc turns a function with the right signature into a get fish handler
type GetFishHandlerFunc func(GetFishParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFishHandlerFunc) Handle(params GetFishParams) middleware.Responder {
	return fn(params)
}

// GetFishHandler interface for that can handle valid get fish params
type GetFishHandler interface {
	Handle(GetFishParams) middleware.Responder
}

// NewGetFish creates a new http.Handler for the get fish operation
func NewGetFish(ctx *middleware.Context, handler GetFishHandler) *GetFish {
	return &GetFish{Context: ctx, Handler: handler}
}

/*GetFish swagger:route GET /catalog/fishes/{id} fish getFish

GetFish get fish API

*/
type GetFish struct {
	Context *middleware.Context
	Handler GetFishHandler
}

func (o *GetFish) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFishParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
