// Code generated by go-swagger; DO NOT EDIT.

package fish

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/yishanhe/animalcrossing-api/models"
)

// GetFishOKCode is the HTTP code returned for type GetFishOK
const GetFishOKCode int = 200

/*GetFishOK return a fish

swagger:response getFishOK
*/
type GetFishOK struct {

	/*
	  In: Body
	*/
	Payload *models.Fish `json:"body,omitempty"`
}

// NewGetFishOK creates GetFishOK with default headers values
func NewGetFishOK() *GetFishOK {

	return &GetFishOK{}
}

// WithPayload adds the payload to the get fish o k response
func (o *GetFishOK) WithPayload(payload *models.Fish) *GetFishOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get fish o k response
func (o *GetFishOK) SetPayload(payload *models.Fish) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFishOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetFishNotFoundCode is the HTTP code returned for type GetFishNotFound
const GetFishNotFoundCode int = 404

/*GetFishNotFound not found

swagger:response getFishNotFound
*/
type GetFishNotFound struct {
}

// NewGetFishNotFound creates GetFishNotFound with default headers values
func NewGetFishNotFound() *GetFishNotFound {

	return &GetFishNotFound{}
}

// WriteResponse to the client
func (o *GetFishNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
