// Code generated by go-swagger; DO NOT EDIT.

package fish

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/yishanhe/animalcrossing-api/models"
)

// ListFishesOKCode is the HTTP code returned for type ListFishesOK
const ListFishesOKCode int = 200

/*ListFishesOK returns a list of fishes

swagger:response listFishesOK
*/
type ListFishesOK struct {

	/*
	  In: Body
	*/
	Payload *models.FishListResult `json:"body,omitempty"`
}

// NewListFishesOK creates ListFishesOK with default headers values
func NewListFishesOK() *ListFishesOK {

	return &ListFishesOK{}
}

// WithPayload adds the payload to the list fishes o k response
func (o *ListFishesOK) WithPayload(payload *models.FishListResult) *ListFishesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list fishes o k response
func (o *ListFishesOK) SetPayload(payload *models.FishListResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListFishesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
