// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// Colors colors
//
// swagger:model Colors
type Colors []string

// Validate validates this colors
func (m Colors) Validate(formats strfmt.Registry) error {
	return nil
}
